Repository Openredu/Openredu, pull requests merged in 2020-06, with the labels that each got.

#269 Altera o README para adicionar informações importantes de contribuição #41
  README.markdown
Labels: exec/pronto pra revisão, merge/squash

#267 Conserta build no Travis CI
  .travis.yml
  README.markdown
  app/models/user.rb
  config/database.travis.yml
  script/grant_travis_privileges_on_mysql.sh
  spec/models/user_spec.rb
  spec/services/status_service/status_mailer_spec.rb
Labels: env/travis, exec/pronto pra revisão, merge/squash

#283 Adiciona scripts pra setup no Mac
  README.markdown
  script/setup/init
  script/setup/run
Labels: exec/pronto pra revisão

#262 WIP: Change subjects presentation order
  app/controllers/spaces_controller.rb
Labels: precisa-se de ajuda/questão
